### ISSUE TITLE
Error when i put the Steam Guard

### ISSUE THREAD

**Issue by goigois1** [MisticJr/steamnode#5]
$ node .
Steam Guard App Code: 6552D
internal/fs/utils.js:781
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (4)
    at Object.writeFile (fs.js:1436:5)
    at FileStorage.saveFile.FileStorage.writeFile (/data/data/com.termux/files/home/main/smurf/steamnode/node_modules/file-manager/index.js:68:5)
    at SteamUser._handlers.<computed> (/data/data/com.termux/files/home/main/smurf/steamnode/node_modules/steam-user/components/logon.js:294:18)
    at SteamUser._handleMessage (/data/data/com.termux/files/home/main/smurf/steamnode/node_modules/steam-user/components/messages.js:249:30)
    at CMClient.emit (events.js:315:20)
    at CMClient._netMsgReceived (/data/data/com.termux/files/home/main/smurf/steamnode/node_modules/steam-client/lib/cm_client.js:323:8)
    at CMClient.handlers.<computed> (/data/data/com.termux/files/home/main/smurf/steamnode/node_modules/steam-client/lib/cm_client.js:609:8)
    at CMClient._netMsgReceived (/data/data/com.termux/files/home/main/smurf/steamnode/node_modules/steam-client/lib/cm_client.js:305:24)
    at TCPConnection.emit (events.js:315:20)
    at TCPConnection._readPacket (/data/data/com.termux/files/home/main/smurf/steamnode/node_modules/steam-client/lib/tcp_connection.js:183:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by MisticJr** [comment]
Go check this link. [https://github.com/SteamTimeIdler/stidler/wiki/Getting-your-%27shared_secret%27-code-for-use-with-Auto-Restarter-on-Mobile-Authentication](Here)

**Comment by goigois1** [comment]
I have shared secret it simply crashes when i put the steam guard

**Comment by goigois1** [comment]
Im using termux, and other scripts work

**Comment by MisticJr** [comment]
make sure to change the Phone_secret in config.json

**Comment by goigois1** [comment]
I put it blank

**Comment by MisticJr** [comment]
yeah you should get the phone secret code from https://github.com/SteamTimeIdler/stidler/wiki/Getting-your-%27shared_secret%27-code-for-use-with-Auto-Restarter-on-Mobile-Authentication

**Comment by goigois1** [comment]
I add the phone secret, it asks for code and crashes

**Comment by MisticJr** [comment]
its forking fine on me tho
